apiVersion: v1
kind: LimitRange
metadata: 
  name: resource-limits
spec:
  limits:
    - type: Pod
      min:
        cpu: 50m
        memory: 5Mi
      max:
        cpu: 1
        memory: 1Gi
    - type: Container
      defaultRequest:
        cpu: 200m
        memory: 100Mi
      default:
        cpu: 400m
        memory: 400Mi
      min:
        cpu: 50m
        memory: 5Mi
      max:
        cpu: 1
        memory: 1Gi
      maxLimitRequestRatio:
        cpu: 4
        memory: 10
    - type: PersistentVolumeClaim
      min:
        storage: 500Mi
      max:
        storage: 10Gi
